version: "3"

services:
  app:
    build: ./app
    image: mlapp:latest
    container_name: mlapp
    env_file:
      - .env
    volumes:
      - ./app:/app 
    depends_on:
      - database
  
  # web-proxy:
  #   image: nginx:stable
  #   depends_on:
  #     - app
  #   ports:
  #   - 80:80
  #   - 443:443

  # rabbitmq:
  #   image: rabbitmq:3-management
  #   ports:
  #     - "15672:15672"  
  #     - "5672:5672"    
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq
  #   restart: always

  database:
    image: postgres:17
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    

  
volumes:
  postgres_data:
  #rabbitmq_data: