version: "3"

services:
  app:
    build: ./app
    env_file:
      - .env
    volumes:
      - ./app:/app 
  
  web-proxy:
    image: nginx:latest
    depends_on:
      - app
    ports:
    - 80:80
    - 443:443

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"  
      - "5672:5672"    
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always

  database:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
volumes:
  postgres_data:
  rabbitmq_data: